server:
  port: 8089

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: library-service-route
          uri: lb://LIBRARY
          predicates:
            - Path=/books/**

        - id: user-service-route
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/users/**

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
